/**
 * @file light_defs.h
 * @author Shujie.Li
 * @version 1.0
 * @brief define const for light
 * @detail define const for light
 */

#ifndef _LIGHT_DEFS_H_
#define _LIGHT_DEFS_H_ 1


static const int CUBIC_LIGHT_KEY_MAX = 16;
typedef enum CubicLightId
{
    CUBIC_LIGHT_ID_WHITE_1 = 0,
    CUBIC_LIGHT_ID_WHITE_2,
    CUBIC_LIGHT_ID_WHITE_3,
    CUBIC_LIGHT_ID_WHITE_4,
    CUBIC_LIGHT_ID_RED_1,
    CUBIC_LIGHT_ID_RED_2,
    CUBIC_LIGHT_ID_RED_3,
    CUBIC_LIGHT_ID_RED_4,
    CUBIC_LIGHT_ID_GREEN_1,
    CUBIC_LIGHT_ID_GREEN_2,
    CUBIC_LIGHT_ID_GREEN_3,
    CUBIC_LIGHT_ID_GREEN_4,
    CUBIC_LIGHT_ID_BLUE_1,
    CUBIC_LIGHT_ID_BLUE_2,
    CUBIC_LIGHT_ID_BLUE_3,
    CUBIC_LIGHT_ID_BLUE_4,
    CUBIC_LIGHT_NUM
} CubicLightId;


static const int CUBIC_LIGHT_BRIGHTNESS_MAX = 255;
static const int CUBIC_LIGHT_BRIGHTNESS_MIN = 0;
static const int CUBIC_LIGHT_BRIGHTNESS_INVALID = -1;

static const char *CUBIC_LIGHT_PATH[CUBIC_LIGHT_NUM] =
{
    "/sys/class/leds/aw9523_led_set_white/brightness",
    NULL,
    NULL,
    NULL,
    "/sys/class/leds/aw9523_led_set_red/brightness",
    NULL,
    NULL,
    NULL,
    "/sys/class/leds/aw9523_led_set_green/brightness",
    NULL,
    NULL,
    NULL,
    "/sys/class/leds/aw9523_led_set_blue/brightness",
    NULL,
    NULL,
    NULL,
};



typedef struct CubicLightKey
{
    int moment;
    int brightness;
} CubicLightKey;

static const CubicLightKey CUBIC_LIGHT_EFFECT_KEEP_LIGHT[CUBIC_LIGHT_KEY_MAX] =
{
    {0,     CUBIC_LIGHT_BRIGHTNESS_MAX},
    {2000,  CUBIC_LIGHT_BRIGHTNESS_MAX},
    { -1,    CUBIC_LIGHT_BRIGHTNESS_INVALID}
};


static const CubicLightKey CUBIC_LIGHT_EFFECT_ACTIVE[CUBIC_LIGHT_KEY_MAX] =
{
    {0,      CUBIC_LIGHT_BRIGHTNESS_MIN},
    {100,    CUBIC_LIGHT_BRIGHTNESS_MAX},
    {200,    CUBIC_LIGHT_BRIGHTNESS_MIN},
    {300,    CUBIC_LIGHT_BRIGHTNESS_MAX},
    {400,    CUBIC_LIGHT_BRIGHTNESS_MIN},
    {2000,   CUBIC_LIGHT_BRIGHTNESS_MIN},
    { -1,    CUBIC_LIGHT_BRIGHTNESS_INVALID}
};

static const CubicLightKey CUBIC_LIGHT_EFFECT_PASSIVE[CUBIC_LIGHT_KEY_MAX] =
{
    {0,      CUBIC_LIGHT_BRIGHTNESS_MIN},
    {2000,   CUBIC_LIGHT_BRIGHTNESS_MAX},
    {3500,   CUBIC_LIGHT_BRIGHTNESS_MIN},
    {7000,   CUBIC_LIGHT_BRIGHTNESS_MIN},
    { -1,    CUBIC_LIGHT_BRIGHTNESS_INVALID}
};

static const CubicLightKey CUBIC_LIGHT_EFFECT_SLEEP[CUBIC_LIGHT_KEY_MAX] =
{
    {0,      CUBIC_LIGHT_BRIGHTNESS_MIN},
    {200,    CUBIC_LIGHT_BRIGHTNESS_MAX},
    {300,    CUBIC_LIGHT_BRIGHTNESS_MIN},
    {500,    CUBIC_LIGHT_BRIGHTNESS_MIN},
    { -1,    CUBIC_LIGHT_BRIGHTNESS_INVALID}
};


static const CubicLightKey CUBIC_LIGHT_EFFECT_FLASH[CUBIC_LIGHT_KEY_MAX] =
{
    {0,     CUBIC_LIGHT_BRIGHTNESS_MIN},
    {500,   CUBIC_LIGHT_BRIGHTNESS_MAX},
    {1000,  CUBIC_LIGHT_BRIGHTNESS_MIN},
    { -1,    CUBIC_LIGHT_BRIGHTNESS_INVALID}
};

static const CubicLightKey CUBIC_LIGHT_EFFECT_QUICK_FLASH[CUBIC_LIGHT_KEY_MAX] =
{
    {0,     CUBIC_LIGHT_BRIGHTNESS_MIN},
    {250,   CUBIC_LIGHT_BRIGHTNESS_MAX},
    {500,   CUBIC_LIGHT_BRIGHTNESS_MIN},
    {750,   CUBIC_LIGHT_BRIGHTNESS_MAX},
    {1000,  CUBIC_LIGHT_BRIGHTNESS_MIN},
    { -1,    CUBIC_LIGHT_BRIGHTNESS_INVALID}
};

static const CubicLightKey CUBIC_LIGHT_EFFECT_ALTENATELY_FLASH_1[CUBIC_LIGHT_KEY_MAX] =
{
    {0,     CUBIC_LIGHT_BRIGHTNESS_MIN},
    {250,   CUBIC_LIGHT_BRIGHTNESS_MAX},
    {500,   CUBIC_LIGHT_BRIGHTNESS_MIN},
    {1000,  CUBIC_LIGHT_BRIGHTNESS_MIN},
    { -1,    CUBIC_LIGHT_BRIGHTNESS_INVALID}
};

static const CubicLightKey CUBIC_LIGHT_EFFECT_ALTENATELY_FLASH_2[CUBIC_LIGHT_KEY_MAX] =
{
    {0,     CUBIC_LIGHT_BRIGHTNESS_MIN},
    {500,   CUBIC_LIGHT_BRIGHTNESS_MIN},
    {750,   CUBIC_LIGHT_BRIGHTNESS_MAX},
    {1000,  CUBIC_LIGHT_BRIGHTNESS_MIN},
    { -1,    CUBIC_LIGHT_BRIGHTNESS_INVALID}
};

static const CubicLightKey CUBIC_LIGHT_EFFECT_BT_FLASH[CUBIC_LIGHT_KEY_MAX] =
{
    {0,     CUBIC_LIGHT_BRIGHTNESS_MIN},
    {50,    CUBIC_LIGHT_BRIGHTNESS_MAX},
    {100,   CUBIC_LIGHT_BRIGHTNESS_MIN},
    {150,   CUBIC_LIGHT_BRIGHTNESS_MAX},
    {200,   CUBIC_LIGHT_BRIGHTNESS_MIN},
    { -1,   CUBIC_LIGHT_BRIGHTNESS_INVALID}
};

static const CubicLightKey CUBIC_LIGHT_EFFECT_OTA_FLASH[CUBIC_LIGHT_KEY_MAX] =
{
    {0,     CUBIC_LIGHT_BRIGHTNESS_MIN},
    {50,    CUBIC_LIGHT_BRIGHTNESS_MAX},
    {100,   CUBIC_LIGHT_BRIGHTNESS_MIN},
    {150,   CUBIC_LIGHT_BRIGHTNESS_MAX},
    {200,   CUBIC_LIGHT_BRIGHTNESS_MIN},
    { -1,   CUBIC_LIGHT_BRIGHTNESS_INVALID}
};

static const CubicLightKey CUBIC_LIGHT_EFFECT_ERR_OTA[CUBIC_LIGHT_KEY_MAX] =
{
    {0,     CUBIC_LIGHT_BRIGHTNESS_MIN},
    {50,    CUBIC_LIGHT_BRIGHTNESS_MAX},
    {100,   CUBIC_LIGHT_BRIGHTNESS_MIN},
    {150,   CUBIC_LIGHT_BRIGHTNESS_MAX},
    {200,   CUBIC_LIGHT_BRIGHTNESS_MIN},
    { -1,   CUBIC_LIGHT_BRIGHTNESS_INVALID}
};

static const CubicLightKey CUBIC_LIGHT_EFFECT_ERR_SIM[CUBIC_LIGHT_KEY_MAX] =
{
    {0,     CUBIC_LIGHT_BRIGHTNESS_MIN},
    {200,   CUBIC_LIGHT_BRIGHTNESS_MAX},
    {400,   CUBIC_LIGHT_BRIGHTNESS_MIN},
    {4000,  CUBIC_LIGHT_BRIGHTNESS_MIN},
    { -1,    CUBIC_LIGHT_BRIGHTNESS_INVALID}
};

static const CubicLightKey CUBIC_LIGHT_EFFECT_ERR_NET[CUBIC_LIGHT_KEY_MAX] =
{
    {0,     CUBIC_LIGHT_BRIGHTNESS_MIN},
    {200,   CUBIC_LIGHT_BRIGHTNESS_MAX},
    {400,   CUBIC_LIGHT_BRIGHTNESS_MIN},
    {600,   CUBIC_LIGHT_BRIGHTNESS_MAX},
    {800,   CUBIC_LIGHT_BRIGHTNESS_MIN},
    {4000,  CUBIC_LIGHT_BRIGHTNESS_MIN},
    { -1,    CUBIC_LIGHT_BRIGHTNESS_INVALID}
};

static const CubicLightKey CUBIC_LIGHT_EFFECT_ERR_ACTIVATE[CUBIC_LIGHT_KEY_MAX] =
{
    {0,     CUBIC_LIGHT_BRIGHTNESS_MIN},
    {200,   CUBIC_LIGHT_BRIGHTNESS_MAX},
    {400,   CUBIC_LIGHT_BRIGHTNESS_MIN},
    {600,   CUBIC_LIGHT_BRIGHTNESS_MAX},
    {800,   CUBIC_LIGHT_BRIGHTNESS_MIN},
    {1000,  CUBIC_LIGHT_BRIGHTNESS_MAX},
    {1200,  CUBIC_LIGHT_BRIGHTNESS_MIN},
    {4000,  CUBIC_LIGHT_BRIGHTNESS_MIN},
    { -1,    CUBIC_LIGHT_BRIGHTNESS_INVALID}
};

static const CubicLightKey CUBIC_LIGHT_EFFECT_ERR_SIP[CUBIC_LIGHT_KEY_MAX] =
{
    {0,     CUBIC_LIGHT_BRIGHTNESS_MIN},
    {200,   CUBIC_LIGHT_BRIGHTNESS_MAX},
    {400,   CUBIC_LIGHT_BRIGHTNESS_MIN},
    {600,   CUBIC_LIGHT_BRIGHTNESS_MAX},
    {800,   CUBIC_LIGHT_BRIGHTNESS_MIN},
    {1000,  CUBIC_LIGHT_BRIGHTNESS_MAX},
    {1200,  CUBIC_LIGHT_BRIGHTNESS_MIN},
    {1400,  CUBIC_LIGHT_BRIGHTNESS_MAX},
    {1600,  CUBIC_LIGHT_BRIGHTNESS_MIN},
    {4000,  CUBIC_LIGHT_BRIGHTNESS_MIN},
    { -1,    CUBIC_LIGHT_BRIGHTNESS_INVALID}
};

static const CubicLightKey CUBIC_LIGHT_EFFECT_RING_1[CUBIC_LIGHT_KEY_MAX] =
{
    {0,     CUBIC_LIGHT_BRIGHTNESS_MAX},
    {500,   CUBIC_LIGHT_BRIGHTNESS_MIN},
    {1500,  CUBIC_LIGHT_BRIGHTNESS_MIN},
    {2000,  CUBIC_LIGHT_BRIGHTNESS_MAX},
    { -1,    CUBIC_LIGHT_BRIGHTNESS_INVALID}
};

static const CubicLightKey CUBIC_LIGHT_EFFECT_RING_2[CUBIC_LIGHT_KEY_MAX] =
{
    {0,     CUBIC_LIGHT_BRIGHTNESS_MIN},
    {500,   CUBIC_LIGHT_BRIGHTNESS_MAX},
    {1000,  CUBIC_LIGHT_BRIGHTNESS_MIN},
    {2000,  CUBIC_LIGHT_BRIGHTNESS_MIN},
    { -1,    CUBIC_LIGHT_BRIGHTNESS_INVALID}
};

static const CubicLightKey CUBIC_LIGHT_EFFECT_RING_3[CUBIC_LIGHT_KEY_MAX] =
{
    {0,     CUBIC_LIGHT_BRIGHTNESS_MIN},
    {500,   CUBIC_LIGHT_BRIGHTNESS_MIN},
    {1000,  CUBIC_LIGHT_BRIGHTNESS_MAX},
    {1500,  CUBIC_LIGHT_BRIGHTNESS_MIN},
    {2000,  CUBIC_LIGHT_BRIGHTNESS_MIN},
    { -1,    CUBIC_LIGHT_BRIGHTNESS_INVALID}
};

static const CubicLightKey CUBIC_LIGHT_EFFECT_RING_4[CUBIC_LIGHT_KEY_MAX] =
{
    {0,     CUBIC_LIGHT_BRIGHTNESS_MIN},
    {1000,  CUBIC_LIGHT_BRIGHTNESS_MIN},
    {1500,  CUBIC_LIGHT_BRIGHTNESS_MAX},
    {2000,  CUBIC_LIGHT_BRIGHTNESS_MIN},
    { -1,    CUBIC_LIGHT_BRIGHTNESS_INVALID}
};


static const CubicLightKey CUBIC_LIGHT_EFFECT_QUICK_RING_1[CUBIC_LIGHT_KEY_MAX] =
{
    {0,     CUBIC_LIGHT_BRIGHTNESS_MAX},
    {200,   CUBIC_LIGHT_BRIGHTNESS_MIN},
    {600,   CUBIC_LIGHT_BRIGHTNESS_MIN},
    {800,   CUBIC_LIGHT_BRIGHTNESS_MAX},
    { -1,    CUBIC_LIGHT_BRIGHTNESS_INVALID}
};

static const CubicLightKey CUBIC_LIGHT_EFFECT_QUICK_RING_2[CUBIC_LIGHT_KEY_MAX] =
{
    {0,     CUBIC_LIGHT_BRIGHTNESS_MIN},
    {200,   CUBIC_LIGHT_BRIGHTNESS_MAX},
    {400,   CUBIC_LIGHT_BRIGHTNESS_MIN},
    {800,   CUBIC_LIGHT_BRIGHTNESS_MIN},
    { -1,    CUBIC_LIGHT_BRIGHTNESS_INVALID}
};

static const CubicLightKey CUBIC_LIGHT_EFFECT_QUICK_RING_3[CUBIC_LIGHT_KEY_MAX] =
{
    {0,     CUBIC_LIGHT_BRIGHTNESS_MIN},
    {200,   CUBIC_LIGHT_BRIGHTNESS_MIN},
    {400,   CUBIC_LIGHT_BRIGHTNESS_MAX},
    {600,   CUBIC_LIGHT_BRIGHTNESS_MIN},
    {800,   CUBIC_LIGHT_BRIGHTNESS_MIN},
    { -1,    CUBIC_LIGHT_BRIGHTNESS_INVALID}
};

static const CubicLightKey CUBIC_LIGHT_EFFECT_QUICK_RING_4[CUBIC_LIGHT_KEY_MAX] =
{
    {0,     CUBIC_LIGHT_BRIGHTNESS_MIN},
    {400,   CUBIC_LIGHT_BRIGHTNESS_MIN},
    {600,   CUBIC_LIGHT_BRIGHTNESS_MAX},
    {800,   CUBIC_LIGHT_BRIGHTNESS_MIN},
    { -1,    CUBIC_LIGHT_BRIGHTNESS_INVALID}
};

#endif //_LIGHT_DEFS_H_

